site_name: SARS-CoV-2 GTG lab documentation
nav:
    - Home: index.md
    - Protocols: protocols.md
    - Sequencing: seq.md
    - Real-time monitoring: realtime.md
    - Analysis: analysis.md
    - Tutorial: tute.md
    - interARTIC: inter.md
theme: readthedocs
